### ISSUE TITLE
Tag Commits?

### ISSUE THREAD

**Issue by dfreeman** [kellyselden/ember-cli-output#1]
This repo has been a huge help in migrating projects between various versions of Ember CLI – thanks for maintaining it!

Have you considered tagging the commits with the corresponding CLI version number? While it's not a huge amount of work to look up the corresponding commit hashes for the versions I'm interested in comparing, tags can provide a nice shortcut, e.g.

https://github.com/ember-cli/ember-cli/compare/v0.2.4...v0.2.5

**Comment by kellyselden** [comment]
sure I could do that

**Comment by kellyselden** [comment]
done

**Comment by dfreeman** [comment]
:heart: Thanks!
